### ISSUE TITLE
Wrong font in .output-cut

### ISSUE THREAD

**Issue by Sumolari** [shockone/black-screen#348]
Font used in `Show all {rows} rows.` text displayed in .output-cut uses default font instead of the font families that should be inherited from `<pre>`:

In `stylesheets/main.scss` `.output-cut` selector extends `.outicon` which generates the following CSS snippet:

```css
.octicon, .output .output-cut, .status-line .current-directory:before, .status-line .vcs-data .status:before, .autocomplete ul li.branch .icon, .mega-octicon {
    font: normal normal normal 16px/1 octicons;
    display: inline-block;
    text-decoration: none;
    text-rendering: auto;
    -webkit-font-smoothing: antialiased;
    -moz-osx-font-smoothing: grayscale;
    -webkit-user-select: none;
    -moz-user-select: none;
    -ms-user-select: none;
    user-select: none;
}
```

It overrides this one, which would be inherited otherwise:

```css
body, pre {
    background-color: #292C33;
    color: #95A2BB;
    font-family: 'Hack', 'Fira Code', 'Meslo LG S for Powerline', 'Menlo', monospace !important;
    font-size: 14px;
    margin: 0;
}
```

Resulting in:

![captura de pantalla 2016-05-22 a las 9 33 30](https://cloud.githubusercontent.com/assets/779767/15452950/edc29eb2-2000-11e6-9429-9f4fc2fc4ec0.png)

An easy fix is making `.output-cut:before` extend `.octicon` instead of `.output-cut` (see [pull request 349](https://github.com/shockone/black-screen/pull/349)), resulting in:

![captura de pantalla 2016-05-22 a las 9 41 11](https://cloud.githubusercontent.com/assets/779767/15452961/57846f06-2001-11e6-9268-f96f49eb1bac.png)
